trigger:
- main

pool:
  vmImage: ubuntu-latest
  
stages: 
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - script: echo Hello, world!
  - job: SecondJob
    steps:
    - script: echo Hello, world!  
      
   
- stage: Dev
- stage: QA
- stage: Prod
  

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
