trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: build
    steps:
    - bash: echo "Do The Build" 
- stage: DevDeploy
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo deploy to dev
- stage: DevDeploy2
  jobs:
  - deployment: DevDeployJob2
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo deploy to dev2            
- stage: QADeploy
  jobs:
  - deployment: QADeployJob
    environment: QA
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy to QA
      

# strategy:
#   matrix:
#     linux:
#       operatingsystem: ubuntu-latest
#     mac:
#       operatingsystem: macos-latest  


# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
